# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# Low memory version for GPUs with limited VRAM
# required >=  3x3090(24G)/4090(24G) with very conservative settings

# Model arguments
model_name_or_path: ./LLM-models-datasets/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./LLM-models-datasets/X-R1-750
dataset_configs:
- train

# GRPO trainer config - Ultra low memory settings
bf16: true
use_vllm: true
vllm_gpu_memory_utilization: 0.15  # 进一步降低VLLM内存使用
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 64  # 大幅增加梯度累积以补偿micro batch
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 128  # 大幅减少prompt长度
num_generations: 2  # GRPO算法要求
max_completion_length: 256  # 大幅减少完成长度
max_steps: -1
num_train_epochs: 3
output_dir: output/X-R1-3B-lowmem
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1  # 保持最小batch size
push_to_hub: False
report_to: []
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1 